spring:
  application:
    name: event-log
  liquibase:
    enabled: false
  cloud:
    gcp:
      pubsub:
        emulator-host: 'localhost:8085'
        project-id: my-test-project
        subscriber:
          max-ack-extension-period: 60
  datasource:
    url: jdbc:postgresql://localhost:5432/event-log-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
use:
  emulator: true

event:
  provider:
    google:
      topic: myTestTopic
      subscriptionInAll: myTestSubscriptionAll
      subscriptionInFirst: myTestSubscription1
      subscriptionInSecond: myTestSubscription2
      subscriptionInThird: myTestSubscription3